/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    AuraButton: typeof import('./components/element/AuraButton.vue')['default']
    BackgroundCanvas: typeof import('./components/BackgroundCanvas.vue')['default']
    ElectricBackground: typeof import('./components/background/ElectricBackground.vue')['default']
    MyBtn: typeof import('./components/MyBtn.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ToggleThemeBtn: typeof import('./components/ToggleThemeBtn.vue')['default']
  }
}
