/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/home/': RouteRecordInfo<'/home/', '/home', Record<never, never>, Record<never, never>>,
    '/home/components/HomePage': RouteRecordInfo<'/home/components/HomePage', '/home/components/HomePage', Record<never, never>, Record<never, never>>,
    '/home/components/SectionFive': RouteRecordInfo<'/home/components/SectionFive', '/home/components/SectionFive', Record<never, never>, Record<never, never>>,
    '/home/components/SectionFour': RouteRecordInfo<'/home/components/SectionFour', '/home/components/SectionFour', Record<never, never>, Record<never, never>>,
    '/home/components/SectionOne': RouteRecordInfo<'/home/components/SectionOne', '/home/components/SectionOne', Record<never, never>, Record<never, never>>,
    '/home/components/SectionThree': RouteRecordInfo<'/home/components/SectionThree', '/home/components/SectionThree', Record<never, never>, Record<never, never>>,
    '/home/components/SectionTwo': RouteRecordInfo<'/home/components/SectionTwo', '/home/components/SectionTwo', Record<never, never>, Record<never, never>>,
    '/lab/': RouteRecordInfo<'/lab/', '/lab', Record<never, never>, Record<never, never>>,
  }
}
